import { ThemeTokens, Token } from "./schema";

export const DEFAULT_TOKENS: ThemeTokens = {
  light: {
    // Semantic Colors (Zinc Light)
    "--background": { h: 0, s: 0, l: 100 },
    "--foreground": { h: 240, s: 10, l: 3.9 },
    "--card": { h: 0, s: 0, l: 100 },
    "--card-foreground": { h: 240, s: 10, l: 3.9 },
    "--popover": { h: 0, s: 0, l: 100 },
    "--popover-foreground": { h: 240, s: 10, l: 3.9 },
    "--primary": { h: 240, s: 5.9, l: 10 },
    "--primary-foreground": { h: 0, s: 0, l: 98 },
    "--secondary": { h: 240, s: 4.8, l: 95.9 },
    "--secondary-foreground": { h: 240, s: 5.9, l: 10 },
    "--muted": { h: 240, s: 4.8, l: 95.9 },
    "--muted-foreground": { h: 240, s: 3.8, l: 46.1 },
    "--accent": { h: 240, s: 4.8, l: 95.9 },
    "--accent-foreground": { h: 240, s: 5.9, l: 10 },
    "--destructive": { h: 0, s: 84.2, l: 60.2 },
    "--destructive-foreground": { h: 0, s: 0, l: 98 },
    "--border": { h: 240, s: 5.9, l: 90 },
    "--input": { h: 240, s: 5.9, l: 90 },
    "--ring": { h: 240, s: 5.9, l: 10 },
    
    // Sidebar
    "--sidebar": { h: 0, s: 0, l: 98.5 },
    "--sidebar-foreground": { h: 240, s: 10, l: 3.9 },
    "--sidebar-primary": { h: 240, s: 5.9, l: 10 },
    "--sidebar-primary-foreground": { h: 0, s: 0, l: 98 },
    "--sidebar-accent": { h: 240, s: 4.8, l: 95.9 },
    "--sidebar-accent-foreground": { h: 240, s: 5.9, l: 10 },
    "--sidebar-border": { h: 240, s: 5.9, l: 90 },
    "--sidebar-ring": { h: 240, s: 5.9, l: 10 },

    // Extended Palette
    "--brand": { h: 240, s: 5.9, l: 10 },
    "--brand-foreground": { h: 0, s: 0, l: 98 },
    "--success": { h: 142.1, s: 76.2, l: 36.3 },
    "--success-foreground": { h: 355.7, s: 100, l: 97.3 },
    "--warning": { h: 47.9, s: 95.8, l: 53.1 },
    "--warning-foreground": { h: 26, s: 83.3, l: 14.1 },
    "--info": { h: 221.2, s: 83.2, l: 53.3 },
    "--info-foreground": { h: 210, s: 40, l: 98 },
    "--surface-1": { h: 0, s: 0, l: 100 },
    "--surface-2": { h: 240, s: 4.8, l: 95.9 },
    "--surface-3": { h: 240, s: 5.9, l: 90 },
    "--chart-1": { h: 12, s: 76, l: 61 },
    "--chart-2": { h: 173, s: 58, l: 39 },
    "--chart-3": { h: 197, s: 37, l: 24 },
    "--chart-4": { h: 43, s: 74, l: 66 },
    "--chart-5": { h: 27, s: 87, l: 67 },

    // Radius
    "--radius": "0.5rem",
    "--radius-sm": "calc(var(--radius) - 2px)",
    "--radius-md": "calc(var(--radius) - 4px)",
    "--radius-lg": "var(--radius)",
    "--radius-xl": "calc(var(--radius) + 4px)",
    "--radius-full": "9999px",

    // Typography
    "--font-sans": "Inter, sans-serif",
    "--font-mono": "Roboto Mono, monospace",
    "--text-xs": "0.75rem",
    "--text-sm": "0.875rem",
    "--text-base": "1rem",
    "--text-lg": "1.125rem",
    "--text-xl": "1.25rem",
    "--text-2xl": "1.5rem",
    "--text-3xl": "1.875rem",
    "--text-4xl": "2.25rem",
    "--font-weight-normal": "400",
    "--font-weight-medium": "500",
    "--font-weight-semibold": "600",
    "--font-weight-bold": "700",
    "--tracking-tighter": "-0.05em",
    "--tracking-tight": "-0.025em",
    "--tracking-normal": "0em",
    "--tracking-wide": "0.025em",
    "--tracking-wider": "0.05em",
    "--tracking-widest": "0.1em",
    "--leading-none": "1",
    "--leading-tight": "1.25",
    "--leading-snug": "1.375",
    "--leading-normal": "1.5",
    "--leading-relaxed": "1.625",
    "--leading-loose": "2",

    // Shadows
    "--shadow-xs": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
    "--shadow-sm": "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
    "--shadow-md": "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
    "--shadow-lg": "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
    "--shadow-xl": "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",

    // Spacing
    "--spacing-1": "0.25rem",
    "--spacing-2": "0.5rem",
    "--spacing-3": "0.75rem",
    "--spacing-4": "1rem",
    "--spacing-5": "1.25rem",
    "--spacing-6": "1.5rem",
    "--spacing-8": "2rem",
    "--spacing-10": "2.5rem",
    "--spacing-12": "3rem",
    "--spacing-16": "4rem",
  },
  dark: {
    // Semantic Colors (Zinc Dark)
    "--background": { h: 240, s: 10, l: 3.9 },
    "--foreground": { h: 0, s: 0, l: 98 },
    "--card": { h: 240, s: 10, l: 3.9 },
    "--card-foreground": { h: 0, s: 0, l: 98 },
    "--popover": { h: 240, s: 10, l: 3.9 },
    "--popover-foreground": { h: 0, s: 0, l: 98 },
    "--primary": { h: 0, s: 0, l: 98 },
    "--primary-foreground": { h: 240, s: 5.9, l: 10 },
    "--secondary": { h: 240, s: 3.7, l: 15.9 },
    "--secondary-foreground": { h: 0, s: 0, l: 98 },
    "--muted": { h: 240, s: 3.7, l: 15.9 },
    "--muted-foreground": { h: 240, s: 5, l: 64.9 },
    "--accent": { h: 240, s: 3.7, l: 15.9 },
    "--accent-foreground": { h: 0, s: 0, l: 98 },
    "--destructive": { h: 0, s: 62.8, l: 30.6 },
    "--destructive-foreground": { h: 0, s: 0, l: 98 },
    "--border": { h: 240, s: 3.7, l: 15.9 },
    "--input": { h: 240, s: 3.7, l: 15.9 },
    "--ring": { h: 240, s: 4.9, l: 83.9 },
    
    // Sidebar
    "--sidebar": { h: 240, s: 10, l: 3.9 },
    "--sidebar-foreground": { h: 0, s: 0, l: 98 },
    "--sidebar-primary": { h: 240, s: 5.9, l: 10 },
    "--sidebar-primary-foreground": { h: 0, s: 0, l: 98 },
    "--sidebar-accent": { h: 240, s: 3.7, l: 15.9 },
    "--sidebar-accent-foreground": { h: 0, s: 0, l: 98 },
    "--sidebar-border": { h: 240, s: 3.7, l: 15.9 },
    "--sidebar-ring": { h: 240, s: 4.9, l: 83.9 },

    // Extended Palette
    "--brand": { h: 0, s: 0, l: 98 },
    "--brand-foreground": { h: 240, s: 5.9, l: 10 },
    "--success": { h: 142.1, s: 70.6, l: 45.3 },
    "--success-foreground": { h: 144.9, s: 80.4, l: 10 },
    "--warning": { h: 47.9, s: 95.8, l: 53.1 },
    "--warning-foreground": { h: 26, s: 83.3, l: 14.1 },
    "--info": { h: 217.2, s: 91.2, l: 59.8 },
    "--info-foreground": { h: 222.2, s: 47.4, l: 11.2 },
    "--surface-1": { h: 240, s: 10, l: 3.9 },
    "--surface-2": { h: 240, s: 3.7, l: 15.9 },
    "--surface-3": { h: 240, s: 4, l: 20 },
    "--chart-1": { h: 220, s: 70, l: 50 },
    "--chart-2": { h: 160, s: 60, l: 45 },
    "--chart-3": { h: 30, s: 80, l: 55 },
    "--chart-4": { h: 280, s: 65, l: 60 },
    "--chart-5": { h: 340, s: 75, l: 55 },

    // Inherited identical for structural/spacing tokens in dark mode
    "--radius": "0.5rem",
    "--radius-sm": "calc(var(--radius) - 2px)",
    "--radius-md": "calc(var(--radius) - 4px)",
    "--radius-lg": "var(--radius)",
    "--radius-xl": "calc(var(--radius) + 4px)",
    "--radius-full": "9999px",
    "--font-sans": "Inter, sans-serif",
    "--font-mono": "Roboto Mono, monospace",
    "--text-xs": "0.75rem",
    "--text-sm": "0.875rem",
    "--text-base": "1rem",
    "--text-lg": "1.125rem",
    "--text-xl": "1.25rem",
    "--text-2xl": "1.5rem",
    "--text-3xl": "1.875rem",
    "--text-4xl": "2.25rem",
    "--font-weight-normal": "400",
    "--font-weight-medium": "500",
    "--font-weight-semibold": "600",
    "--font-weight-bold": "700",
    "--tracking-tighter": "-0.05em",
    "--tracking-tight": "-0.025em",
    "--tracking-normal": "0em",
    "--tracking-wide": "0.025em",
    "--tracking-wider": "0.05em",
    "--tracking-widest": "0.1em",
    "--leading-none": "1",
    "--leading-tight": "1.25",
    "--leading-snug": "1.375",
    "--leading-normal": "1.5",
    "--leading-relaxed": "1.625",
    "--leading-loose": "2",
    "--shadow-xs": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
    "--shadow-sm": "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
    "--shadow-md": "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
    "--shadow-lg": "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
    "--shadow-xl": "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
    "--spacing-1": "0.25rem",
    "--spacing-2": "0.5rem",
    "--spacing-3": "0.75rem",
    "--spacing-4": "1rem",
    "--spacing-5": "1.25rem",
    "--spacing-6": "1.5rem",
    "--spacing-8": "2rem",
    "--spacing-10": "2.5rem",
    "--spacing-12": "3rem",
    "--spacing-16": "4rem",
  }
};

export const TOKEN_DEFINITIONS: Token[] = [
  // Semantic Colors
  { id: "--background", cssVar: "--background", label: "Background", description: "Default background color of <body />...", type: "color", group: "semantic-colors", supportsAlpha: true, editable: true },
  { id: "--foreground", cssVar: "--foreground", label: "Foreground", description: "Default text color.", type: "color", group: "semantic-colors", supportsAlpha: true, editable: true },
  { id: "--card", cssVar: "--card", label: "Card", description: "Background color for cards", type: "color", group: "semantic-colors", supportsAlpha: true, editable: true },
  { id: "--card-foreground", cssVar: "--card-foreground", label: "Card Foreground", description: "Text color for cards", type: "color", group: "semantic-colors", supportsAlpha: true, editable: true },
  { id: "--popover", cssVar: "--popover", label: "Popover", description: "Background color for popovers such as dropdowns", type: "color", group: "semantic-colors", supportsAlpha: true, editable: true },
  { id: "--popover-foreground", cssVar: "--popover-foreground", label: "Popover Foreground", description: "Text color for popovers", type: "color", group: "semantic-colors", supportsAlpha: true, editable: true },
  { id: "--primary", cssVar: "--primary", label: "Primary", description: "Primary colors for <Button />", type: "color", group: "semantic-colors", supportsAlpha: true, editable: true },
  { id: "--primary-foreground", cssVar: "--primary-foreground", label: "Primary Foreground", description: "Text color for primary buttons", type: "color", group: "semantic-colors", supportsAlpha: true, editable: true },
  { id: "--secondary", cssVar: "--secondary", label: "Secondary", description: "Secondary colors for <Button />", type: "color", group: "semantic-colors", supportsAlpha: true, editable: true },
  { id: "--secondary-foreground", cssVar: "--secondary-foreground", label: "Secondary Foreground", description: "Text color for secondary buttons", type: "color", group: "semantic-colors", supportsAlpha: true, editable: true },
  { id: "--muted", cssVar: "--muted", label: "Muted", description: "Muted backgrounds such as <TabsList />", type: "color", group: "semantic-colors", supportsAlpha: true, editable: true },
  { id: "--muted-foreground", cssVar: "--muted-foreground", label: "Muted Foreground", description: "Muted text colors", type: "color", group: "semantic-colors", supportsAlpha: true, editable: true },
  { id: "--accent", cssVar: "--accent", label: "Accent", description: "Used for accents such as hover effects", type: "color", group: "semantic-colors", supportsAlpha: true, editable: true },
  { id: "--accent-foreground", cssVar: "--accent-foreground", label: "Accent Foreground", description: "Text color for accents", type: "color", group: "semantic-colors", supportsAlpha: true, editable: true },
  { id: "--destructive", cssVar: "--destructive", label: "Destructive", description: "Used for destructive actions", type: "color", group: "semantic-colors", supportsAlpha: true, editable: true },
  { id: "--destructive-foreground", cssVar: "--destructive-foreground", label: "Destructive Foreground", description: "Text color for destructive actions", type: "color", group: "semantic-colors", supportsAlpha: true, editable: true },
  { id: "--border", cssVar: "--border", label: "Border", description: "Default border color", type: "color", group: "semantic-colors", supportsAlpha: true, editable: true },
  { id: "--input", cssVar: "--input", label: "Input", description: "Border color for inputs like <Input />", type: "color", group: "semantic-colors", supportsAlpha: true, editable: true },
  { id: "--ring", cssVar: "--ring", label: "Ring", description: "Focus ring color", type: "color", group: "semantic-colors", supportsAlpha: true, editable: true },

  // Sidebar
  { id: "--sidebar", cssVar: "--sidebar", label: "Sidebar", description: "Sidebar background color", type: "color", group: "sidebar", supportsAlpha: true, editable: true },
  { id: "--sidebar-foreground", cssVar: "--sidebar-foreground", label: "Sidebar Foreground", description: "Text color within the sidebar", type: "color", group: "sidebar", supportsAlpha: true, editable: true },
  { id: "--sidebar-primary", cssVar: "--sidebar-primary", label: "Sidebar Primary", description: "Active/primary item background in sidebar", type: "color", group: "sidebar", supportsAlpha: true, editable: true },
  { id: "--sidebar-primary-foreground", cssVar: "--sidebar-primary-foreground", label: "Sidebar Primary Foreground", description: "Text on active sidebar items", type: "color", group: "sidebar", supportsAlpha: true, editable: true },
  { id: "--sidebar-accent", cssVar: "--sidebar-accent", label: "Sidebar Accent", description: "Hover/accent color for sidebar items", type: "color", group: "sidebar", supportsAlpha: true, editable: true },
  { id: "--sidebar-accent-foreground", cssVar: "--sidebar-accent-foreground", label: "Sidebar Accent Foreground", description: "Text on hovered sidebar items", type: "color", group: "sidebar", supportsAlpha: true, editable: true },
  { id: "--sidebar-border", cssVar: "--sidebar-border", label: "Sidebar Border", description: "Border and separator colors in sidebar", type: "color", group: "sidebar", supportsAlpha: true, editable: true },
  { id: "--sidebar-ring", cssVar: "--sidebar-ring", label: "Sidebar Ring", description: "Focus ring color within sidebar", type: "color", group: "sidebar", supportsAlpha: true, editable: true },

  // Extended Palette
  { id: "--brand", cssVar: "--brand", label: "Brand", description: "Main brand color", type: "color", group: "extended-palette", supportsAlpha: true, editable: true },
  { id: "--brand-foreground", cssVar: "--brand-foreground", label: "Brand Foreground", description: "Text color for brand backgrounds", type: "color", group: "extended-palette", supportsAlpha: true, editable: true },
  { id: "--success", cssVar: "--success", label: "Success", description: "Success state color", type: "color", group: "extended-palette", supportsAlpha: true, editable: true },
  { id: "--success-foreground", cssVar: "--success-foreground", label: "Success Foreground", description: "Text color for success states", type: "color", group: "extended-palette", supportsAlpha: true, editable: true },
  { id: "--warning", cssVar: "--warning", label: "Warning", description: "Warning state color", type: "color", group: "extended-palette", supportsAlpha: true, editable: true },
  { id: "--warning-foreground", cssVar: "--warning-foreground", label: "Warning Foreground", description: "Text color for warning states", type: "color", group: "extended-palette", supportsAlpha: true, editable: true },
  { id: "--info", cssVar: "--info", label: "Info", description: "Informational state color", type: "color", group: "extended-palette", supportsAlpha: true, editable: true },
  { id: "--info-foreground", cssVar: "--info-foreground", label: "Info Foreground", description: "Text color for info states", type: "color", group: "extended-palette", supportsAlpha: true, editable: true },
  { id: "--surface-1", cssVar: "--surface-1", label: "Surface 1", description: "Layer 1 surface", type: "color", group: "extended-palette", supportsAlpha: true, editable: true },
  { id: "--surface-2", cssVar: "--surface-2", label: "Surface 2", description: "Layer 2 surface", type: "color", group: "extended-palette", supportsAlpha: true, editable: true },
  { id: "--surface-3", cssVar: "--surface-3", label: "Surface 3", description: "Layer 3 surface", type: "color", group: "extended-palette", supportsAlpha: true, editable: true },
  { id: "--chart-1", cssVar: "--chart-1", label: "Chart 1", description: "Chart color 1", type: "color", group: "extended-palette", supportsAlpha: true, editable: true },
  { id: "--chart-2", cssVar: "--chart-2", label: "Chart 2", description: "Chart color 2", type: "color", group: "extended-palette", supportsAlpha: true, editable: true },
  { id: "--chart-3", cssVar: "--chart-3", label: "Chart 3", description: "Chart color 3", type: "color", group: "extended-palette", supportsAlpha: true, editable: true },
  { id: "--chart-4", cssVar: "--chart-4", label: "Chart 4", description: "Chart color 4", type: "color", group: "extended-palette", supportsAlpha: true, editable: true },
  { id: "--chart-5", cssVar: "--chart-5", label: "Chart 5", description: "Chart color 5", type: "color", group: "extended-palette", supportsAlpha: true, editable: true },

  // Radius
  { id: "--radius", cssVar: "--radius", label: "Base Radius", description: "Base border radius", type: "radius", group: "radius", supportsAlpha: false, editable: true },
  { id: "--radius-sm", cssVar: "--radius-sm", label: "Small Radius", description: "Small border radius", type: "radius", group: "radius", supportsAlpha: false, editable: true },
  { id: "--radius-md", cssVar: "--radius-md", label: "Medium Radius", description: "Medium border radius", type: "radius", group: "radius", supportsAlpha: false, editable: true },
  { id: "--radius-lg", cssVar: "--radius-lg", label: "Large Radius", description: "Large border radius", type: "radius", group: "radius", supportsAlpha: false, editable: true },
  { id: "--radius-xl", cssVar: "--radius-xl", label: "XL Radius", description: "Extra large border radius", type: "radius", group: "radius", supportsAlpha: false, editable: true },
  { id: "--radius-full", cssVar: "--radius-full", label: "Full Radius", description: "Full (pill) border radius", type: "radius", group: "radius", supportsAlpha: false, editable: true },

  // Typography
  { id: "--font-sans", cssVar: "--font-sans", label: "Sans Font", description: "Base sans-serif font family", type: "fontFamily", group: "typography", supportsAlpha: false, editable: true },
  { id: "--font-mono", cssVar: "--font-mono", label: "Mono Font", description: "Monospace font family", type: "fontFamily", group: "typography", supportsAlpha: false, editable: true },
  { id: "--text-xs", cssVar: "--text-xs", label: "Text XS", description: "Extra small font size", type: "fontSize", group: "typography", supportsAlpha: false, editable: true },
  { id: "--text-sm", cssVar: "--text-sm", label: "Text SM", description: "Small font size", type: "fontSize", group: "typography", supportsAlpha: false, editable: true },
  { id: "--text-base", cssVar: "--text-base", label: "Text Base", description: "Base font size", type: "fontSize", group: "typography", supportsAlpha: false, editable: true },
  { id: "--text-lg", cssVar: "--text-lg", label: "Text LG", description: "Large font size", type: "fontSize", group: "typography", supportsAlpha: false, editable: true },
  { id: "--text-xl", cssVar: "--text-xl", label: "Text XL", description: "Extra large font size", type: "fontSize", group: "typography", supportsAlpha: false, editable: true },
  { id: "--text-2xl", cssVar: "--text-2xl", label: "Text 2XL", description: "2XL font size", type: "fontSize", group: "typography", supportsAlpha: false, editable: true },
  { id: "--text-3xl", cssVar: "--text-3xl", label: "Text 3XL", description: "3XL font size", type: "fontSize", group: "typography", supportsAlpha: false, editable: true },
  { id: "--text-4xl", cssVar: "--text-4xl", label: "Text 4XL", description: "4XL font size", type: "fontSize", group: "typography", supportsAlpha: false, editable: true },
  { id: "--font-weight-normal", cssVar: "--font-weight-normal", label: "Normal Weight", description: "Normal font weight", type: "fontWeight", group: "typography", supportsAlpha: false, editable: true },
  { id: "--font-weight-medium", cssVar: "--font-weight-medium", label: "Medium Weight", description: "Medium font weight", type: "fontWeight", group: "typography", supportsAlpha: false, editable: true },
  { id: "--font-weight-semibold", cssVar: "--font-weight-semibold", label: "Semibold Weight", description: "Semibold font weight", type: "fontWeight", group: "typography", supportsAlpha: false, editable: true },
  { id: "--font-weight-bold", cssVar: "--font-weight-bold", label: "Bold Weight", description: "Bold font weight", type: "fontWeight", group: "typography", supportsAlpha: false, editable: true },
  { id: "--tracking-tighter", cssVar: "--tracking-tighter", label: "Tracking Tighter", description: "Tighter letter spacing", type: "spacing", group: "typography", supportsAlpha: false, editable: true },
  { id: "--tracking-tight", cssVar: "--tracking-tight", label: "Tracking Tight", description: "Tight letter spacing", type: "spacing", group: "typography", supportsAlpha: false, editable: true },
  { id: "--tracking-normal", cssVar: "--tracking-normal", label: "Tracking Normal", description: "Normal letter spacing", type: "spacing", group: "typography", supportsAlpha: false, editable: true },
  { id: "--tracking-wide", cssVar: "--tracking-wide", label: "Tracking Wide", description: "Wide letter spacing", type: "spacing", group: "typography", supportsAlpha: false, editable: true },
  { id: "--tracking-wider", cssVar: "--tracking-wider", label: "Tracking Wider", description: "Wider letter spacing", type: "spacing", group: "typography", supportsAlpha: false, editable: true },
  { id: "--tracking-widest", cssVar: "--tracking-widest", label: "Tracking Widest", description: "Widest letter spacing", type: "spacing", group: "typography", supportsAlpha: false, editable: true },
  { id: "--leading-none", cssVar: "--leading-none", label: "Leading None", description: "Line height 1", type: "lineHeight", group: "typography", supportsAlpha: false, editable: true },
  { id: "--leading-tight", cssVar: "--leading-tight", label: "Leading Tight", description: "Tight line height", type: "lineHeight", group: "typography", supportsAlpha: false, editable: true },
  { id: "--leading-snug", cssVar: "--leading-snug", label: "Leading Snug", description: "Snug line height", type: "lineHeight", group: "typography", supportsAlpha: false, editable: true },
  { id: "--leading-normal", cssVar: "--leading-normal", label: "Leading Normal", description: "Normal line height", type: "lineHeight", group: "typography", supportsAlpha: false, editable: true },
  { id: "--leading-relaxed", cssVar: "--leading-relaxed", label: "Leading Relaxed", description: "Relaxed line height", type: "lineHeight", group: "typography", supportsAlpha: false, editable: true },
  { id: "--leading-loose", cssVar: "--leading-loose", label: "Leading Loose", description: "Loose line height", type: "lineHeight", group: "typography", supportsAlpha: false, editable: true },

  // Shadows
  { id: "--shadow-xs", cssVar: "--shadow-xs", label: "Shadow XS", description: "Extra small shadow", type: "shadow", group: "shadows", supportsAlpha: false, editable: true },
  { id: "--shadow-sm", cssVar: "--shadow-sm", label: "Shadow SM", description: "Small shadow", type: "shadow", group: "shadows", supportsAlpha: false, editable: true },
  { id: "--shadow-md", cssVar: "--shadow-md", label: "Shadow MD", description: "Medium shadow", type: "shadow", group: "shadows", supportsAlpha: false, editable: true },
  { id: "--shadow-lg", cssVar: "--shadow-lg", label: "Shadow LG", description: "Large shadow", type: "shadow", group: "shadows", supportsAlpha: false, editable: true },
  { id: "--shadow-xl", cssVar: "--shadow-xl", label: "Shadow XL", description: "Extra large shadow", type: "shadow", group: "shadows", supportsAlpha: false, editable: true },

  // Spacing
  { id: "--spacing-1", cssVar: "--spacing-1", label: "Spacing 1", description: "0.25rem spacing", type: "spacing", group: "spacing", supportsAlpha: false, editable: true },
  { id: "--spacing-2", cssVar: "--spacing-2", label: "Spacing 2", description: "0.5rem spacing", type: "spacing", group: "spacing", supportsAlpha: false, editable: true },
  { id: "--spacing-3", cssVar: "--spacing-3", label: "Spacing 3", description: "0.75rem spacing", type: "spacing", group: "spacing", supportsAlpha: false, editable: true },
  { id: "--spacing-4", cssVar: "--spacing-4", label: "Spacing 4", description: "1rem spacing", type: "spacing", group: "spacing", supportsAlpha: false, editable: true },
  { id: "--spacing-5", cssVar: "--spacing-5", label: "Spacing 5", description: "1.25rem spacing", type: "spacing", group: "spacing", supportsAlpha: false, editable: true },
  { id: "--spacing-6", cssVar: "--spacing-6", label: "Spacing 6", description: "1.5rem spacing", type: "spacing", group: "spacing", supportsAlpha: false, editable: true },
  { id: "--spacing-8", cssVar: "--spacing-8", label: "Spacing 8", description: "2rem spacing", type: "spacing", group: "spacing", supportsAlpha: false, editable: true },
  { id: "--spacing-10", cssVar: "--spacing-10", label: "Spacing 10", description: "2.5rem spacing", type: "spacing", group: "spacing", supportsAlpha: false, editable: true },
  { id: "--spacing-12", cssVar: "--spacing-12", label: "Spacing 12", description: "3rem spacing", type: "spacing", group: "spacing", supportsAlpha: false, editable: true },
  { id: "--spacing-16", cssVar: "--spacing-16", label: "Spacing 16", description: "4rem spacing", type: "spacing", group: "spacing", supportsAlpha: false, editable: true },
];
