import { ThemeTokens, CustomToken, TokenValue } from "../tokens/schema";
import { hslToCssString, isHSLValue } from "../colorUtils";
import { TOKEN_DEFINITIONS } from "../tokens/defaults";

function formatValue(value: TokenValue | undefined): string {
  if (value === undefined) return "";
  if (isHSLValue(value)) return hslToCssString(value);
  return String(value);
}

export function exportToCss(tokens: ThemeTokens, customTokens: CustomToken[]): string {
  let lightBlock = "";
  let darkBlock = "";

  const allDefinitions = [...TOKEN_DEFINITIONS, ...customTokens];

  for (const def of allDefinitions) {
    const lightVal = tokens.light[def.cssVar];
    if (lightVal !== undefined && lightVal !== "") {
      lightBlock += `    ${def.cssVar}: ${formatValue(lightVal)};\n`;
    }

    const darkVal = tokens.dark[def.cssVar];
    if (darkVal !== undefined && darkVal !== "") {
      darkBlock += `    ${def.cssVar}: ${formatValue(darkVal)};\n`;
    }
  }

  return `/* Generated by Theme Studio — https://themestudio.dev */

@layer base {
  :root {
${lightBlock.trimEnd()}
  }

  .dark {
${darkBlock.trimEnd()}
  }
}
`;
}
