"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.exportToCss = exportToCss;
const colorUtils_1 = require("../colorUtils");
const defaults_1 = require("../tokens/defaults");
function formatValue(value) {
    if (value === undefined)
        return "";
    if ((0, colorUtils_1.isHSLValue)(value))
        return (0, colorUtils_1.hslToCssString)(value);
    return String(value);
}
function exportToCss(tokens, customTokens) {
    let lightBlock = "";
    let darkBlock = "";
    const allDefinitions = [...defaults_1.TOKEN_DEFINITIONS, ...customTokens];
    for (const def of allDefinitions) {
        const lightVal = tokens.light[def.cssVar];
        if (lightVal !== undefined && lightVal !== "") {
            lightBlock += `    ${def.cssVar}: ${formatValue(lightVal)};\n`;
        }
        const darkVal = tokens.dark[def.cssVar];
        if (darkVal !== undefined && darkVal !== "") {
            darkBlock += `    ${def.cssVar}: ${formatValue(darkVal)};\n`;
        }
    }
    return `/* Generated by Theme Studio — https://themestudio.dev */

@layer base {
  :root {
${lightBlock.trimEnd()}
  }

  .dark {
${darkBlock.trimEnd()}
  }
}
`;
}
