// scripts/smoke-test.ts
// Run with: npx tsx scripts/smoke-test.ts

import { hslToHex, hexToHsl, hslToCssString, 
         cssStringToHsl, remToPx, hslToRgbFloat } from "../src/lib/colorUtils"
import { DEFAULT_TOKENS, TOKEN_DEFINITIONS } from "../src/lib/tokens/defaults"
import { PRESETS, getPreset } from "../src/lib/tokens/presets"
import { exportToCodebase } from "../src/lib/export/toCodebase"
import { exportToFigma } from "../src/lib/export/toFigma"
import { exportToCss } from "../src/lib/export/toCss"

let passed = 0
let failed = 0

function assert(label: string, actual: unknown, expected: unknown) {
  const ok = JSON.stringify(actual) === JSON.stringify(expected)
  if (ok) {
    console.log(`  ✅ ${label}`)
    passed++
  } else {
    console.log(`  ❌ ${label}`)
    console.log(`     expected: ${JSON.stringify(expected)}`)
    console.log(`     received: ${JSON.stringify(actual)}`)
    failed++
  }
}

function assertApprox(label: string, actual: number, expected: number, tolerance = 0.005) {
  const ok = Math.abs(actual - expected) <= tolerance
  if (ok) {
    console.log(`  ✅ ${label}`)
    passed++
  } else {
    console.log(`  ❌ ${label}`)
    console.log(`     expected: ~${expected}, received: ${actual}`)
    failed++
  }
}

// ── Color Utils ──────────────────────────────────────────────────
console.log("\n🎨 colorUtils")
assert("white hex",    hslToHex({ h: 0, s: 0, l: 100 }),   "#ffffff")
assert("black hex",    hslToHex({ h: 0, s: 0, l: 0 }),     "#000000")
assert("white hexToHsl", hexToHsl("#ffffff").l,             100)
assert("black hexToHsl", hexToHsl("#000000").l,             0)
assert("css string",   hslToCssString({ h: 222, s: 47, l: 11 }), "222 47% 11%")
assert("css parse h",  cssStringToHsl("222 47% 11%").h,    222)
assert("css parse s",  cssStringToHsl("222 47% 11%").s,    47)
assert("css parse l",  cssStringToHsl("222 47% 11%").l,    11)
assert("remToPx str",  remToPx("0.5rem"),                  8)
assert("remToPx num",  remToPx(1.5),                       24)

const rgb = hslToRgbFloat({ h: 240, s: 5.9, l: 10 })
assertApprox("figma r", rgb.r, 0.094)
assertApprox("figma g", rgb.g, 0.094)
assertApprox("figma b", rgb.b, 0.102)

// ── Token Completeness ────────────────────────────────────────────
console.log("\n📦 defaults")
const lightKeys  = Object.keys(DEFAULT_TOKENS.light)
const darkKeys   = Object.keys(DEFAULT_TOKENS.dark)
assert("light/dark key parity", lightKeys.sort(), darkKeys.sort())
assert("has --primary",     lightKeys.includes("--primary"),    true)
assert("has --background",  lightKeys.includes("--background"), true)
assert("has --radius",      lightKeys.includes("--radius"),     true)
assert("token defs match",  
  TOKEN_DEFINITIONS.every(t => lightKeys.includes(t.cssVar)), true)

// ── Presets ───────────────────────────────────────────────────────
console.log("\n🎨 presets")
assert("5 presets",          PRESETS.length >= 5,              true)
assert("default preset",     !!getPreset("default"),           true)
assert("rose preset",        !!getPreset("rose"),              true)
assert("preset has light",   !!getPreset("default")?.tokens.light, true)

// ── Exports ───────────────────────────────────────────────────────
console.log("\n📤 exports")
const codebaseJson = JSON.parse(exportToCodebase(DEFAULT_TOKENS, []))
assert("codebase has light",        !!codebaseJson.light,      true)
assert("codebase has dark",         !!codebaseJson.dark,       true)
assert("codebase primary format",   
  typeof codebaseJson.light["--primary"] === "string" &&
  codebaseJson.light["--primary"].includes("%"),               true)

const figmaJson = JSON.parse(exportToFigma(DEFAULT_TOKENS, []))
assert("figma has collections",     !!figmaJson.collections,   true)
assert("figma has variables",       
  figmaJson.collections[0].variables.length > 0,              true)

const css = exportToCss(DEFAULT_TOKENS, [])
assert("css has :root",     css.includes(":root"),             true)
assert("css has .dark",     css.includes(".dark"),             true)
assert("css has comment",   css.includes("Generated by"),      true)

// ── Summary ───────────────────────────────────────────────────────
console.log(`\n${"─".repeat(40)}`)
console.log(`  ${passed} passed  |  ${failed} failed`)
if (failed > 0) process.exit(1)
